export const APP_SELECT = 'APP_SELECT';
export const PLACEMENT_SELECT = 'PLACEMENT_SELECT';
export const PLACEMENT_SETTINGS_CHANGED = 'PLACEMENT_SETTINGS_CHANGED';
export const PLACEMENT_SETTINGS_RESET = 'PLACEMENT_SETTINGS_RESET';
export const REMEMBER_PLACEMENT_TO_GO_AFTER_CONFIRM = 'REMEMBER_PLACEMENT_TO_GO_AFTER_CONFIRM';
export const PLACEMENT_TO_DELETE_UPDATE = 'PLACEMENT_TO_DELETE_UPDATE';
